name: Update Docs

on:
    push:
        # branches:
        #     - main
        #     - Klehrik-luajit-3

jobs:
    generate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Checkout wiki repo
              uses: actions/checkout@v4
              with:
                repository: ReturnsAPI/ReturnsAPI.wiki
                token: ${{ secrets.GITHUB_TOKEN }}
                path: wiki

            - name: Run parser and copy out to wiki repo
              run: |
                python docs/main.py
                cp docs/out/* wiki/

            - name: Push changes to wiki repo
              working-directory: wiki
              run: |
                git config user.name "github-actions"
                git config user.email "github-actions@github.com"
                git add .
                git commit -m "Update docs" || echo "No docs changes"
                git push