name: Update Docs

on:
    push:
        branches:
            - docs-testing

jobs:
    generate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: What is in here
              run: ls -R

            - name: Give directory perms
              run: chmod u+rwx docs/out

            - name: Run parser
              run: python docs/main.py