name: Update Docs

on:
    push:
        branches:
            - docs-testing

jobs:
    generate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Give directory perms
              run: chmod docs/out u+rwx

            - name: Run parser
              run: python docs/main.py