name: Update Docs

on:
    push:
        branches:
            - docs-testing

jobs:
    generate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Make docs/out
              run: mkdir -p docs/out

            - name: Run parser
              run: python docs/main.py