name: Update Docs

on:
    push:
        branches:
            - docs-testing

jobs:
    generate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - run: ls -lR

            - name: Run parser
              run: python docs/main.py
              
            - run: ls -lR