name: Update Docs

on:
    push:
        branches:
            - docs-testing

jobs:
    generate:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Run parser
              run: python docs/main.py
            #   run: ls -R