name: Update Docs

on:
    push:
        branches:
            - docs-testing

jobs:
    generate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Run parser
              run: python docs/main.py

            # - name: Push changes to repo
            #   run: |
            #     git config user.name "github-actions"
            #     git config user.email "github-actions@github.com"
            #     git add docs/out
            #     git commit -m "Update docs"
            #     git push